### ISSUE TITLE
bug: 24 hour limit for edit button doesn't work

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/neospring#18]
I posted a response a few hours ago and went back to edit it, but I couldn't because it said "You can only edit responses within 24 hours of posting it" when I had just posted it earlier... I don't know if this makes sense sorry.

**Comment by trisuaso** [comment]
This seems to be working fine currently, so it's likely either an issue with this specific response, or an issue with the times.

Please double-check the time of the response (the one at the bottom)!

**Comment by trisuaso** [comment]
Stale, also likely resolved.
