### ISSUE TITLE
PLEASE HELP; I can't log into my account! 

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/neospring#19]
I don't know where else to contact for help or support, I can't remember my password and everything I try is denied. At one point I had tried to change my password but it said it wasn't allowed and now my original password isn't working and I can't remember what I wrote as the new password. I have proof that the account is mine, please if there is any way to contact someone so I can show proof, I have discord twitter gmail please help me I don't know what to do 😞😞

**Comment by fleshorchestra** [comment]
I was able to log in after many many attempts but my friend is having the same issue so I'd still like to be able to help him 😢 Please respond if theres any way to contact for support properly about this!

**Comment by trisuaso** [comment]
Email support@swmff.org.
