### ISSUE TITLE
feature: Separate profile settings for Mobile and PC

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/neospring#20]
I've started to notice that Sparkler (on mobile) only fits certain widths for banners, unlike Retrospring which would automatically fit the banner width to the phone screen. I think it would be great to be able to choose, on mobile, options like "Fit to screen width" or "Align to left ／ right ／ center" like Carrd.co has in settings for images. This would make viewing peoples profiles on different devices a lot more accessible and user friendly across devices.

For example, my banner is 1200 by 180 px (W:H), but on mobile it extends outside of the page. 
![banner](https://github.com/user-attachments/assets/1264a079-19f5-45f4-8a4c-da443ab1cf4a)

Here are screenshot examples of how my profile looks on PC versus mobile.
![image](https://github.com/user-attachments/assets/e9401135-74c0-4a54-9bac-2966efa89b84)
![IMG_1613](https://github.com/user-attachments/assets/bd2ad723-324a-4e5d-8134-0cc4576e0388)

Here is an example of how I would like my banner to look on mobile, without changing its size or quality or PC.
![IMG_1613](https://github.com/user-attachments/assets/cf83f1ce-b029-4a62-82d0-9e629a2efdd8)

**Comment by trisuaso** [comment]
Added, thanks!

0fd33e5
