### ISSUE TITLE
bug: Emojis have a circle border???

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/neospring#21]
All emojis posted in answers seem to be shaped as a circle/there is some sort of circle mask over all emojis, and causes them to be misshapen... I don't know if I am explaining this well
![image](https://github.com/user-attachments/assets/855c67ec-ca3c-47a1-8d5f-2e03babea2d6)

**Comment by fleshorchestra** [comment]
Here is what those emojis look like normally: 🤍🇵🇸

**Comment by fleshorchestra** [comment]
![Screenshot_20240915_162504_Chrome](https://github.com/user-attachments/assets/5d400b68-84f2-46dc-af43-14acd2646074)
Another screenshot from my friend who is also experiencing this

**Comment by trisuaso** [comment]
Fixed in b6f8d9d, thanks!
