### ISSUE TITLE
feature: Return to inbox

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/neospring#22]
Like Retrospring, I think it would be beneficial to have questions return to your inbox when you delete the response to them on your profile, so you can re-answer it again if the edit time limit has expired.

**Comment by trisuaso** [comment]
Great idea (which is actually possible now)! Will be added at some point tomorrow.

Questions made before we updated the response format will not be able to be sent back to the inbox. We could possibly use a time limit of something like 24 hours to avoid abuse?

**Comment by fleshorchestra** [comment]
I think a 24 hour limit might make the feature ineffective since the edit button has the same purpose and time restraint, because let's say a month passes and a person's account aesthetic changes, it'd be nice to go back and re-answer the question so that way the formatting stays up to date

**Comment by trisuaso** [comment]
Fair, no limit then. Will be done tomorrow!

**Comment by trisuaso** [comment]
Added 24bc0fc
