### ISSUE TITLE
bug: Grayscale "edit profile" button

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/neospring#24]
I don't know if this is intentional but it is personally extremely annoying when looking at my profile. 

The "Edit profile" button is always in grayscale, no matter what image or hex code you put under the "primary" setting. In the code, it's written as： a class="button round-lg w-full bold primary grayscale"
By removing the 'grayscale' at the end of the code by using inspect element, the edit button gains color again. 

I know this is small and very nitpick-y, but it personally bothers me a lot when it comes to creating my theme.

**Comment by trisuaso** [comment]
Done!
